#!/bin/bash

[[ ! -d ~/bin ]] && mkdir ~/bin
[[ ! -d ~/lib/dictionary ]] && mkdir -p ~/lib/dictionary
[[ ! -d ~/var/dictionary ]] && mkdir -p ~/var/dictionary
[[ ! -d ~/log/dictionary ]] && mkdir -p ~/log/dictionary
cp dict ~/bin/dict
cp dict.rb ~/lib/dictionary/dict.rb
if [[ ! -f ~/var/dictionary/dict.txt ]]
then
  cp dict.txt ~/var/dictionary/dict.txt
else
  echo "Existing dictionary will not be overwritten."
fi
cp help.txt ~/var/dictionary/help.txt
touch ~/log/dictionary/dictionary.log
